builds:
  - binary: blessclient
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - '-w -s -X github.com/Benbentwo/blessclient/pkg/util.GitSha={{.Commit}} -X github.com/Benbentwo/blessclient/pkg/util.Version={{.Version}} -X github.com/Benbentwo/blessclient/pkg/util.Dirty=false -X github.com/Benbentwo/blessclient/pkg/util.Release=true'

archives:
  - files:
      - none*

release:
  prerelease: true
  github:
    owner: Benbentwo
    name: blessclient

env_files:
  github_token: ~/.config/goreleaser/github_token
