builds:
  - binary: blessclient
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - '-w -s -X github.com/Benbentwo/blessclient/pkg/util.GitSha={{.Commit}} -X github.com/Benbentwo/blessclient/pkg/util.Version={{.Version}} -X github.com/Benbentwo/blessclient/pkg/util.Dirty=false -X github.com/Benbentwo/blessclient/pkg/util.Release=true'

archives:
  - files:
      - none*

release:
  github:
    owner: Benbentwo
    name: blessclient

brews:
  - description: 'SSH without pain.'
    name: blessclient@1
    github:
      owner: Benbentwo
      name: homebrew-tap
    homepage: 'https://github.com/Benbentwo/blessclient'
    test: system "#{bin}/blessclient version"

env_files:
  github_token: ~/.config/goreleaser/github_token
