regions: []
clientconfig:
  clientdir: config.yml
  cachedir: config.yml/cache
  mfacachefile: mfa-cache.json
  kmsauthcachefile: kmsauth-cache.json
lambdaconfig:
  awsprofile: bless
  certlifetime:
    duration: 5m0s
  functionname: shared-infra-prod-bless
